# Generated by Django 5.0.6 on 2025-09-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
