# Generated by Django 5.0.6 on 2025-09-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_juguete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='juguetes/'),
        ),
    ]
