# Generated by Django 5.0.6 on 2025-09-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_juguete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='juguete/'),
        ),
        migrations.AlterField(
            model_name='juguete',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juguete', to='app.proveedor'),
        ),
    ]
