# Generated by Django 5.0.6 on 2025-09-16 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_juguete_image_alter_juguete_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/templates/media/juguetes/'),
        ),
        migrations.AlterField(
            model_name='juguete',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juguetes', to='app.proveedor'),
        ),
    ]
