# Generated by Django 5.0.6 on 2025-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_juguete_image_alter_juguete_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/juguetes/'),
        ),
    ]
