# Generated by Django 5.0.6 on 2025-09-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_juguete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='juguetes/'),
        ),
    ]
