# Generated by Django 5.0.6 on 2025-09-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_juguete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juguete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/templates/media/juguetes/'),
        ),
    ]
