name: Build and Tests

on:
  pull_request:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

  static-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run static test
        run: ruff check

  unit-and-integration-tests:
    needs: static-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests
        run: coverage run --source="./app" --omit="./app/migrations/**" manage.py test app
      - name: Check coverage
        run: coverage report --fail-under=84

  e2e:
    needs: unit-and-integration-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Start Django development server
        run: |
          python manage.py runserver 0.0.0.0:8000 &
          echo $! > django_pid.txt
      - name: Install Playwright browsers
        run: |
          playwright install
      - name: Run E2E tests
        run: python manage.py test functional_tests
      - name: Stop Django development server
        run: kill $(cat django_pid.txt)